### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mfrederickson** [KPB-US/badgeulator#6]
- [X] use disable-with, show working...especially in regards to take, crop and print.  
- [X] buttons at bottom in their own div, all together
- [x] dont regen user badge when generating design preview
